# Generated by GitHub Copilot
"""
RetinaIQ â€” Comprehensive evaluation with test-time augmentation (TTA).

Features
--------
  â€¢ Test-time augmentation (TTA): averages N augmented passes + 1 clean pass for more
    robust probability estimates (+0.5â€“2 % accuracy vs single-pass)
  â€¢ Full metric suite: Accuracy, AUC (macro OvR), F1-macro, QWK, per-class P / R / F1
  â€¢ Three publication-ready plots saved to ml_models/evaluation/:
      confusion_matrix.png    normalised (recall) + raw counts side-by-side
      roc_curves.png          per-class OvR ROC curves with AUC annotations
      metrics_summary.png     horizontal bar chart of key scores
  â€¢ metrics.json              machine-readable results

Usage
-----
    # Best accuracy (TTA=8, default):
    python evaluate.py --dataset_path /path/to/dataset \\
                       --weights ml_models/retinaiq_efficientnetv2b3_best.h5

    # Fast single-pass:
    python evaluate.py --dataset_path /path/to/dataset \\
                       --weights ml_models/retinaiq_efficientnetv2b3_best.h5 --tta 1

    # Different backbone:
    python evaluate.py --dataset_path /path/to/dataset \\
                       --weights ml_models/retinaiq_efficientnetb0_best.h5 --model efficientnetb0

Note: --image_size must match the value used during training (default: 300).
"""

import argparse
import csv
import json
import random
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    accuracy_score,
    auc as compute_auc,
    classification_report,
    cohen_kappa_score,
    confusion_matrix,
    f1_score,
    roc_auc_score,
    roc_curve,
)
from sklearn.preprocessing import label_binarize

DR_GRADES_SHORT = ["No DR", "Mild", "Moderate", "Severe", "Proliferative"]
_PALETTE = ["#2196F3", "#4CAF50", "#FF9800", "#F44336", "#9C27B0"]


# â”€â”€ Data utilities (identical split logic to train.py â€” same seed = same test set) â”€â”€

def _find_image_file(images_dir: Path, image_id: str) -> Path | None:
    for ext in (".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"):
        p = images_dir / f"{image_id}{ext}"
        if p.exists():
            return p
    return None


def _load_samples(dataset_path: Path) -> list[tuple[str, int]]:
    csv_path = dataset_path / "train.csv"
    if not csv_path.exists():
        raise FileNotFoundError(f"train.csv not found at: {csv_path}")

    images_dir = dataset_path / "train_images"
    if not images_dir.exists():
        images_dir = dataset_path / "images"
    if not images_dir.exists():
        raise FileNotFoundError("Image folder not found in dataset path.")

    rows: list[tuple[str, int]] = []
    with csv_path.open("r", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            img_id = str(row.get("id_code", "")).strip()
            label = int(str(row.get("diagnosis", "0")).strip())
            p = _find_image_file(images_dir, img_id)
            if p is not None:
                rows.append((str(p), label))

    if not rows:
        raise RuntimeError("No usable samples found.")
    return rows


def _stratified_split(
    samples: list[tuple[str, int]],
    val_ratio: float = 0.15,
    test_ratio: float = 0.15,
) -> tuple[list[tuple[str, int]], list[tuple[str, int]], list[tuple[str, int]]]:
    by_class: dict[int, list[tuple[str, int]]] = {i: [] for i in range(5)}
    for s in samples:
        by_class[s[1]].append(s)

    train, val, test = [], [], []
    for items in by_class.values():
        if not items:
            continue
        random.shuffle(items)
        n = len(items)
        nv = max(1, int(n * val_ratio)) if n >= 3 else 1
        nt = max(1, int(n * test_ratio)) if n >= 3 else 1
        ntr = max(1, n - nv - nt)
        train.extend(items[:ntr])
        val.extend(items[ntr : ntr + nv])
        test.extend(items[ntr + nv :])

    random.shuffle(train)
    random.shuffle(val)
    random.shuffle(test)
    return train, val, test


def _build_dataset(
    samples: list[tuple[str, int]],
    batch_size: int,
    image_size: int,
    augment: bool = False,
) -> tf.data.Dataset:
    paths = [s[0] for s in samples]
    labels = [s[1] for s in samples]
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))

    def _decode(path: tf.Tensor, label: tf.Tensor) -> tuple[tf.Tensor, tf.Tensor]:
        img = tf.io.read_file(path)
        img = tf.io.decode_image(img, channels=3, expand_animations=False)
        img = tf.image.resize(img, [image_size, image_size])
        img = tf.cast(img, tf.float32) / 255.0
        return img, tf.one_hot(tf.cast(label, tf.int32), depth=5)

    ds = ds.map(_decode, num_parallel_calls=tf.data.AUTOTUNE)
    if augment:
        # Mild augmentation for TTA â€” enough variety without distorting signal
        tta_aug = tf.keras.Sequential([
            tf.keras.layers.RandomFlip("horizontal_and_vertical"),
            tf.keras.layers.RandomRotation(0.25),
            tf.keras.layers.RandomZoom((-0.08, 0.05)),
            tf.keras.layers.RandomBrightness(0.10),
            tf.keras.layers.RandomContrast(0.15),
        ])
        ds = ds.map(
            lambda x, y: (tta_aug(x, training=True), y),
            num_parallel_calls=tf.data.AUTOTUNE,
        )

    return ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)


def _build_model(model_name: str, image_size: int) -> tf.keras.Model:
    """Identical architecture to train.py â€” must match exactly for weight loading."""
    backbones = {
        "efficientnetv2b3": tf.keras.applications.EfficientNetV2B3,
        "efficientnetb0": tf.keras.applications.EfficientNetB0,
        "mobilenetv3": tf.keras.applications.MobileNetV3Large,
        "densenet121": tf.keras.applications.DenseNet121,
    }
    if model_name not in backbones:
        raise ValueError(f"Unknown model '{model_name}'.")

    # weights=None â€” we load from file; no need to download ImageNet weights
    backbone = backbones[model_name](
        weights=None, include_top=False,
        input_shape=(image_size, image_size, 3), name="backbone",
    )

    gap = tf.keras.layers.GlobalAveragePooling2D()(backbone.output)
    gmp = tf.keras.layers.GlobalMaxPooling2D()(backbone.output)
    x = tf.keras.layers.Concatenate()([gap, gmp])
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dense(512, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.4)(x)
    x = tf.keras.layers.Dense(256, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.3)(x)
    out = tf.keras.layers.Dense(5, activation="softmax", dtype="float32")(x)

    return tf.keras.Model(inputs=backbone.input, outputs=out)


# â”€â”€ Prediction â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

def _predict_tta(
    model: tf.keras.Model,
    samples: list[tuple[str, int]],
    batch_size: int,
    image_size: int,
    n_tta: int,
) -> np.ndarray:
    """Average probabilities over n_tta total passes (1 clean + n_tta-1 augmented).

    A value of n_tta=1 means no augmentation (clean pass only).
    Higher values improve calibration at the cost of inference time.
    """
    clean_ds = _build_dataset(samples, batch_size, image_size, augment=False)
    all_probs = [model.predict(clean_ds, verbose=0)]

    if n_tta > 1:
        print(f"  Running {n_tta - 1} TTA augmented pass(es)...")
        for _ in range(n_tta - 1):
            aug_ds = _build_dataset(samples, batch_size, image_size, augment=True)
            all_probs.append(model.predict(aug_ds, verbose=0))

    return np.mean(all_probs, axis=0)


# â”€â”€ Plots â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

def _plot_confusion_matrix(y_true: np.ndarray, y_pred: np.ndarray, out_dir: Path) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))

    cm_raw = confusion_matrix(y_true, y_pred)
    ConfusionMatrixDisplay(confusion_matrix=cm_raw, display_labels=DR_GRADES_SHORT).plot(
        ax=axes[0], xticks_rotation=30, colorbar=False, cmap="Blues"
    )
    axes[0].set_title("Confusion Matrix (counts)", fontsize=13, fontweight="bold")

    cm_norm = confusion_matrix(y_true, y_pred, normalize="true")
    ConfusionMatrixDisplay(confusion_matrix=cm_norm, display_labels=DR_GRADES_SHORT).plot(
        ax=axes[1], xticks_rotation=30, colorbar=False, cmap="Blues"
    )
    axes[1].set_title("Confusion Matrix (normalised â€” row = recall)", fontsize=13, fontweight="bold")

    plt.suptitle("5-Class DR Grading â€” Test Set", fontsize=14, fontweight="bold", y=1.01)
    plt.tight_layout()
    path = out_dir / "confusion_matrix.png"
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {path}")


def _plot_roc_curves(y_true: np.ndarray, y_prob: np.ndarray, out_dir: Path) -> None:
    y_bin = label_binarize(y_true, classes=list(range(5)))
    fig, ax = plt.subplots(figsize=(9, 7))

    for i, (grade, color) in enumerate(zip(DR_GRADES_SHORT, _PALETTE)):
        fpr, tpr, _ = roc_curve(y_bin[:, i], y_prob[:, i])
        roc_auc = compute_auc(fpr, tpr)
        ax.plot(fpr, tpr, color=color, lw=2, label=f"{grade}  (AUC = {roc_auc:.3f})")

    ax.plot([0, 1], [0, 1], "k--", lw=1, alpha=0.4)
    ax.set_xlim([-0.01, 1.0])
    ax.set_ylim([0.0, 1.01])
    ax.set_xlabel("False Positive Rate", fontsize=12)
    ax.set_ylabel("True Positive Rate", fontsize=12)
    ax.set_title("Per-Class ROC Curves (One-vs-Rest)", fontsize=13, fontweight="bold")
    ax.legend(loc="lower right", fontsize=10)
    ax.grid(alpha=0.3)
    path = out_dir / "roc_curves.png"
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {path}")


def _plot_metrics_bar(metrics: dict, out_dir: Path) -> None:
    entries = [
        ("Accuracy",          metrics["accuracy"]),
        ("F1 Macro",          metrics["f1_macro"]),
        ("QWK (quadratic)",   metrics["qwk"]),
    ]
    if metrics.get("auc_macro_ovr") is not None:
        entries.insert(1, ("AUC (macro OvR)", metrics["auc_macro_ovr"]))

    labels = [e[0] for e in entries]
    values = [e[1] for e in entries]
    colors = _PALETTE[: len(entries)]

    fig, ax = plt.subplots(figsize=(8, max(4, len(entries) * 0.9)))
    bars = ax.barh(labels, values, color=colors, height=0.5, edgecolor="white")
    for bar, val in zip(bars, values):
        ax.text(
            bar.get_width() + 0.005,
            bar.get_y() + bar.get_height() / 2,
            f"{val:.4f}",
            va="center", fontsize=11, fontweight="bold",
        )
    ax.set_xlim(0, 1.14)
    ax.set_xlabel("Score", fontsize=11)
    ax.set_title("Evaluation Metrics â€” Test Set", fontsize=13, fontweight="bold")
    ax.axvline(x=0.80, color="gray", linestyle="--", alpha=0.5, label="0.80 reference")
    ax.legend(fontsize=9)
    ax.grid(axis="x", alpha=0.3)
    plt.tight_layout()
    path = out_dir / "metrics_summary.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved: {path}")


# â”€â”€ Entry point â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate a trained RetinaIQ model.")
    parser.add_argument("--dataset_path", required=True, help="Path to APTOS-style dataset.")
    parser.add_argument("--weights", required=True, help="Path to saved .h5 weights file.")
    parser.add_argument(
        "--model",
        default="efficientnetv2b3",
        choices=["efficientnetv2b3", "efficientnetb0", "mobilenetv3", "densenet121"],
        help="Backbone used during training (default: efficientnetv2b3).",
    )
    parser.add_argument("--batch_size", type=int, default=16)
    parser.add_argument(
        "--image_size", type=int, default=300,
        help="Input image size â€” must match the value used during training (default: 300).",
    )
    parser.add_argument(
        "--tta", type=int, default=8,
        help="TTA passes: 1 clean + (tta-1) augmented. Use 1 for fast single-pass (default: 8).",
    )
    args = parser.parse_args()

    random.seed(42)
    tf.random.set_seed(42)
    np.random.seed(42)

    dataset_path = Path(args.dataset_path).expanduser().resolve()
    print(f"\nDataset : {dataset_path}")
    samples = _load_samples(dataset_path)
    _, _, test_samples = _stratified_split(samples)
    print(f"Test samples: {len(test_samples)}")

    print(f"Building '{args.model}' and loading weights: {args.weights}")
    model = _build_model(args.model, args.image_size)
    model.load_weights(args.weights)

    print(f"\nPredicting with TTA={args.tta} pass(es)...")
    y_prob = _predict_tta(model, test_samples, args.batch_size, args.image_size, args.tta)
    y_pred = np.argmax(y_prob, axis=1)
    y_true = np.array([label for _, label in test_samples])

    # â”€â”€ Metrics â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    acc  = float(accuracy_score(y_true, y_pred))
    f1   = float(f1_score(y_true, y_pred, average="macro", zero_division=0))
    qwk  = float(cohen_kappa_score(y_true, y_pred, weights="quadratic"))
    try:
        auc_macro: float | None = float(
            roc_auc_score(y_true, y_prob, average="macro", multi_class="ovr")
        )
    except ValueError:
        auc_macro = None

    report_dict = classification_report(
        y_true, y_pred, target_names=DR_GRADES_SHORT, output_dict=True, zero_division=0
    )

    metrics: dict = {
        "model": args.model,
        "weights": args.weights,
        "tta_passes": args.tta,
        "test_samples": len(test_samples),
        "accuracy": round(acc, 4),
        "auc_macro_ovr": round(auc_macro, 4) if auc_macro is not None else None,
        "f1_macro": round(f1, 4),
        "qwk": round(qwk, 4),
        "per_class": {
            grade: {
                "precision": round(report_dict[grade]["precision"], 4),
                "recall":    round(report_dict[grade]["recall"],    4),
                "f1":        round(report_dict[grade]["f1-score"],  4),
                "support":   int(report_dict[grade]["support"]),
            }
            for grade in DR_GRADES_SHORT
        },
    }

    # â”€â”€ Console summary â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    auc_str = f"{auc_macro:.4f}" if auc_macro is not None else "N/A"
    print(f"\n{'='*58}")
    print(f"  {'Metric':<28} {'Value':>10}")
    print(f"  {'-'*38}")
    print(f"  {'Accuracy':<28} {acc:>10.4f}")
    print(f"  {'AUC (macro OvR)':<28} {auc_str:>10}")
    print(f"  {'F1 Macro':<28} {f1:>10.4f}")
    print(f"  {'QWK (quadratic kappa)':<28} {qwk:>10.4f}")
    print(f"\n  {'Per-class breakdown':}")
    print(f"  {'Class':<18} {'Precision':>10} {'Recall':>8} {'F1':>8} {'Support':>9}")
    print(f"  {'-'*53}")
    for grade in DR_GRADES_SHORT:
        pc = metrics["per_class"][grade]
        print(
            f"  {grade:<18} {pc['precision']:>10.4f} {pc['recall']:>8.4f}"
            f" {pc['f1']:>8.4f} {pc['support']:>9}"
        )
    print(f"{'='*58}\n")

    # â”€â”€ Save outputs â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    out_dir = Path("./ml_models/evaluation")
    out_dir.mkdir(parents=True, exist_ok=True)

    metrics_path = out_dir / "metrics.json"
    metrics_path.write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    print(f"Metrics  saved: {metrics_path}")

    print("Generating plots...")
    _plot_confusion_matrix(y_true, y_pred, out_dir)
    _plot_roc_curves(y_true, y_prob, out_dir)
    _plot_metrics_bar(metrics, out_dir)

    print(f"\nAll outputs in: {out_dir.resolve()}\n")


if __name__ == "__main__":
    main()

