# Generated by GitHub Copilot
"""Evaluate a trained RetinaIQ model on an APTOS-style dataset.

Loads the same deterministic test split used during training (seed=42) so results
are directly comparable to the test scores printed by train.py.

Usage:
    python evaluate.py --dataset_path /path/to/dataset --weights ml_models/retinaiq_efficientnetv2b3.h5
    python evaluate.py --dataset_path /path/to/dataset --weights ml_models/retinaiq_efficientnetb0.h5 --model efficientnetb0

Outputs (saved to ./ml_models/evaluation/):
    metrics.json           accuracy, AUC, F1-macro, QWK
    confusion_matrix.png   confusion matrix heatmap
"""

import argparse
import csv
import json
import random
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    accuracy_score,
    cohen_kappa_score,
    confusion_matrix,
    f1_score,
    roc_auc_score,
)

DR_GRADES = ["No DR", "Mild NPDR", "Moderate NPDR", "Severe NPDR", "Proliferative DR"]


def _find_image_file(images_dir: Path, image_id: str) -> Path | None:
    for ext in (".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"):
        candidate = images_dir / f"{image_id}{ext}"
        if candidate.exists():
            return candidate
    return None


def _load_samples(dataset_path: Path) -> list[tuple[str, int]]:
    csv_path = dataset_path / "train.csv"
    if not csv_path.exists():
        raise FileNotFoundError(f"train.csv not found at: {csv_path}")

    images_dir = dataset_path / "train_images"
    if not images_dir.exists():
        images_dir = dataset_path / "images"
    if not images_dir.exists():
        raise FileNotFoundError(
            "Could not find image folder. Expected train_images/ or images/ under dataset path."
        )

    rows: list[tuple[str, int]] = []
    with csv_path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            image_id = str(row.get("id_code", "")).strip()
            diagnosis = int(str(row.get("diagnosis", "0")).strip())
            image_path = _find_image_file(images_dir, image_id)
            if image_path is not None:
                rows.append((str(image_path), diagnosis))

    if not rows:
        raise RuntimeError("No usable samples found. Check dataset path and image files.")
    return rows


def _stratified_split(
    samples: list[tuple[str, int]], val_ratio: float = 0.15, test_ratio: float = 0.15
) -> tuple[list[tuple[str, int]], list[tuple[str, int]], list[tuple[str, int]]]:
    """Identical split logic to train.py — use the same seed to get the same test set."""
    by_class: dict[int, list[tuple[str, int]]] = {i: [] for i in range(5)}
    for sample in samples:
        by_class[sample[1]].append(sample)

    train: list[tuple[str, int]] = []
    val: list[tuple[str, int]] = []
    test: list[tuple[str, int]] = []

    for label, items in by_class.items():
        if not items:
            continue
        random.shuffle(items)
        n_total = len(items)
        n_val = max(1, int(n_total * val_ratio)) if n_total >= 3 else 1
        n_test = max(1, int(n_total * test_ratio)) if n_total >= 3 else 1
        n_train = max(1, n_total - n_val - n_test)

        train.extend(items[:n_train])
        val.extend(items[n_train : n_train + n_val])
        test.extend(items[n_train + n_val :])

    random.shuffle(train)
    random.shuffle(val)
    random.shuffle(test)
    return train, val, test


def _build_dataset(samples: list[tuple[str, int]], batch_size: int) -> tf.data.Dataset:
    paths = [s[0] for s in samples]
    labels = [s[1] for s in samples]
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))

    def _decode(path: tf.Tensor, label: tf.Tensor) -> tuple[tf.Tensor, tf.Tensor]:
        img = tf.io.read_file(path)
        img = tf.io.decode_image(img, channels=3, expand_animations=False)
        img = tf.image.resize(img, [300, 300])
        img = tf.cast(img, tf.float32) / 255.0
        return img, tf.one_hot(tf.cast(label, tf.int32), depth=5)

    return (
        ds.map(_decode, num_parallel_calls=tf.data.AUTOTUNE)
        .batch(batch_size)
        .prefetch(tf.data.AUTOTUNE)
    )


def _build_model(model_name: str) -> tf.keras.Model:
    """Build the same model architecture as train.py (weights loaded separately)."""
    backbones = {
        "efficientnetv2b3": tf.keras.applications.EfficientNetV2B3,
        "efficientnetb0": tf.keras.applications.EfficientNetB0,
        "mobilenetv3": tf.keras.applications.MobileNetV3Large,
        "densenet121": tf.keras.applications.DenseNet121,
    }
    if model_name not in backbones:
        raise ValueError(f"Unsupported model '{model_name}'. Choose from: {', '.join(backbones)}")

    # Use weights=None — we load from file, we don't need ImageNet re-init
    backbone = backbones[model_name](weights=None, include_top=False, input_shape=(300, 300, 3))
    backbone.trainable = False

    x = tf.keras.layers.GlobalAveragePooling2D()(backbone.output)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dense(512, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.5)(x)
    x = tf.keras.layers.Dense(256, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.4)(x)
    x = tf.keras.layers.Dense(128, activation="relu")(x)
    x = tf.keras.layers.Dropout(0.3)(x)
    out = tf.keras.layers.Dense(5, activation="softmax")(x)

    return tf.keras.Model(inputs=backbone.input, outputs=out)


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate a trained RetinaIQ model.")
    parser.add_argument("--dataset_path", required=True, help="Path to APTOS-style dataset.")
    parser.add_argument("--weights", required=True, help="Path to saved model weights (.h5).")
    parser.add_argument(
        "--model",
        default="efficientnetv2b3",
        choices=["efficientnetv2b3", "efficientnetb0", "mobilenetv3", "densenet121"],
        help="Backbone architecture used during training.",
    )
    parser.add_argument("--batch_size", type=int, default=16)
    args = parser.parse_args()

    # Use the same seed as train.py so the test split is identical
    random.seed(42)
    tf.random.set_seed(42)

    dataset_path = Path(args.dataset_path).expanduser().resolve()
    print(f"Loading dataset from: {dataset_path}")
    samples = _load_samples(dataset_path)
    _, _, test_samples = _stratified_split(samples)
    print(f"Test samples: {len(test_samples)}")

    print(f"Building model '{args.model}' and loading weights from: {args.weights}")
    model = _build_model(args.model)
    model.load_weights(args.weights)

    test_ds = _build_dataset(test_samples, args.batch_size)
    y_true = np.array([label for _, label in test_samples])

    print("Running predictions...")
    y_prob = model.predict(test_ds, verbose=1)
    y_pred = np.argmax(y_prob, axis=1)

    # Core metrics
    acc = accuracy_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred, average="macro", zero_division=0)
    qwk = cohen_kappa_score(y_true, y_pred, weights="quadratic")

    # AUC macro OvR — handle edge case where a class is absent from test set
    try:
        auc = float(roc_auc_score(y_true, y_prob, average="macro", multi_class="ovr"))
    except ValueError:
        auc = float("nan")

    metrics = {
        "model": args.model,
        "weights": args.weights,
        "test_samples": int(len(test_samples)),
        "accuracy": round(float(acc), 4),
        "auc_macro_ovr": round(auc, 4) if not np.isnan(auc) else None,
        "f1_macro": round(float(f1), 4),
        "qwk": round(float(qwk), 4),
    }

    print("\n--- Evaluation Results ---")
    for k, v in metrics.items():
        print(f"  {k}: {v}")

    # Persist outputs
    out_dir = Path("./ml_models/evaluation")
    out_dir.mkdir(parents=True, exist_ok=True)

    metrics_path = out_dir / "metrics.json"
    metrics_path.write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    print(f"\nMetrics saved to: {metrics_path}")

    # Confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    fig, ax = plt.subplots(figsize=(8, 6))
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=DR_GRADES)
    disp.plot(ax=ax, xticks_rotation=45, colorbar=False)
    ax.set_title(f"Confusion Matrix — {args.model}")
    plt.tight_layout()
    cm_path = out_dir / "confusion_matrix.png"
    fig.savefig(cm_path, dpi=150)
    plt.close(fig)
    print(f"Confusion matrix saved to: {cm_path}")


if __name__ == "__main__":
    main()
