# Generated by GitHub Copilot
"""RetinaIQ single-command training pipeline for APTOS-style datasets.

Usage:
    python train.py --dataset_path /path/to/dataset
    python train.py --dataset_path /path/to/dataset --model efficientnetv2b3 --epochs 20 --batch_size 16

Dataset layout expected:
    <dataset_path>/
        train.csv          (columns: id_code, diagnosis)
        train_images/      (or images/)
            <id_code>.png
            ...

Outputs (saved to ./ml_models/):
    retinaiq_<model>.h5        model weights
    training_history.json      per-epoch metrics + final test scores
"""

import argparse
import csv
import json
import random
from pathlib import Path

import tensorflow as tf


def _find_image_file(images_dir: Path, image_id: str) -> Path | None:
    """Find image path by id across common retinal image file extensions."""
    for ext in (".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"):
        candidate = images_dir / f"{image_id}{ext}"
        if candidate.exists():
            return candidate
    return None


def _load_samples(dataset_path: Path) -> list[tuple[str, int]]:
    """Load APTOS-style CSV and resolve available image files."""
    csv_path = dataset_path / "train.csv"
    if not csv_path.exists():
        raise FileNotFoundError(f"train.csv not found at: {csv_path}")

    images_dir = dataset_path / "train_images"
    if not images_dir.exists():
        images_dir = dataset_path / "images"
    if not images_dir.exists():
        raise FileNotFoundError(
            "Could not find image folder. Expected train_images/ or images/ under dataset path."
        )

    rows: list[tuple[str, int]] = []
    with csv_path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            image_id = str(row.get("id_code", "")).strip()
            diagnosis = int(str(row.get("diagnosis", "0")).strip())
            image_path = _find_image_file(images_dir, image_id)
            if image_path is not None:
                rows.append((str(image_path), diagnosis))

    if not rows:
        raise RuntimeError("No usable samples found. Check dataset path and image files.")
    return rows


def _stratified_split(
    samples: list[tuple[str, int]], val_ratio: float = 0.15, test_ratio: float = 0.15
) -> tuple[list[tuple[str, int]], list[tuple[str, int]], list[tuple[str, int]]]:
    """Split samples into train/val/test while preserving per-class balance."""
    by_class: dict[int, list[tuple[str, int]]] = {i: [] for i in range(5)}
    for sample in samples:
        by_class[sample[1]].append(sample)

    train: list[tuple[str, int]] = []
    val: list[tuple[str, int]] = []
    test: list[tuple[str, int]] = []

    for label, items in by_class.items():
        if not items:
            continue
        random.shuffle(items)
        n_total = len(items)
        n_val = max(1, int(n_total * val_ratio)) if n_total >= 3 else 1
        n_test = max(1, int(n_total * test_ratio)) if n_total >= 3 else 1
        n_train = max(1, n_total - n_val - n_test)

        train.extend(items[:n_train])
        val.extend(items[n_train : n_train + n_val])
        test.extend(items[n_train + n_val :])

    random.shuffle(train)
    random.shuffle(val)
    random.shuffle(test)
    return train, val, test


def _build_dataset(
    samples: list[tuple[str, int]], batch_size: int, training: bool
) -> tf.data.Dataset:
    """Build TensorFlow dataset pipeline with decode, resize, normalize, and optional augmentation."""
    paths = [s[0] for s in samples]
    labels = [s[1] for s in samples]
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))

    def _decode(path: tf.Tensor, label: tf.Tensor) -> tuple[tf.Tensor, tf.Tensor]:
        img = tf.io.read_file(path)
        img = tf.io.decode_image(img, channels=3, expand_animations=False)
        img = tf.image.resize(img, [300, 300])
        img = tf.cast(img, tf.float32) / 255.0
        return img, tf.one_hot(tf.cast(label, tf.int32), depth=5)

    ds = ds.map(_decode, num_parallel_calls=tf.data.AUTOTUNE)
    if training:
        augmenter = tf.keras.Sequential(
            [
                tf.keras.layers.RandomFlip("horizontal"),
                tf.keras.layers.RandomRotation(0.08),
                tf.keras.layers.RandomZoom(0.1),
                tf.keras.layers.RandomContrast(0.1),
            ]
        )
        ds = ds.map(
            lambda x, y: (augmenter(x, training=True), y),
            num_parallel_calls=tf.data.AUTOTUNE,
        )
        ds = ds.shuffle(max(len(samples), batch_size * 4))

    return ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)


def _build_model(model_name: str) -> tf.keras.Model:
    """Construct selected backbone with classification head for 5-class DR grading."""
    backbones = {
        "efficientnetv2b3": tf.keras.applications.EfficientNetV2B3,
        "efficientnetb0": tf.keras.applications.EfficientNetB0,
        "mobilenetv3": tf.keras.applications.MobileNetV3Large,
        "densenet121": tf.keras.applications.DenseNet121,
    }
    if model_name not in backbones:
        raise ValueError(f"Unsupported model '{model_name}'. Choose from: {', '.join(backbones)}")

    backbone = backbones[model_name](weights="imagenet", include_top=False, input_shape=(300, 300, 3))
    backbone.trainable = False

    x = tf.keras.layers.GlobalAveragePooling2D()(backbone.output)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dense(512, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.5)(x)
    x = tf.keras.layers.Dense(256, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.4)(x)
    x = tf.keras.layers.Dense(128, activation="relu")(x)
    x = tf.keras.layers.Dropout(0.3)(x)
    out = tf.keras.layers.Dense(5, activation="softmax")(x)

    model = tf.keras.Model(inputs=backbone.input, outputs=out)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
        loss=tf.keras.losses.CategoricalCrossentropy(),
        metrics=["accuracy", tf.keras.metrics.AUC(name="auc")],
    )
    return model


def _class_weights(train_samples: list[tuple[str, int]]) -> dict[int, float]:
    """Compute inverse-frequency class weights for imbalanced DR grade distribution."""
    counts = {i: 0 for i in range(5)}
    for _, label in train_samples:
        counts[label] += 1
    total = sum(counts.values())
    weights: dict[int, float] = {}
    for k, v in counts.items():
        weights[k] = 1.0 if v == 0 else (total / (5.0 * v))
    return weights


def main() -> None:
    """Train selected model from dataset path and persist model weights + metadata."""
    parser = argparse.ArgumentParser(description="Train a DR grading model.")
    parser.add_argument("--dataset_path", required=True, help="Path to APTOS-style dataset.")
    parser.add_argument(
        "--model",
        default="efficientnetv2b3",
        choices=["efficientnetv2b3", "efficientnetb0", "mobilenetv3", "densenet121"],
        help="Backbone architecture.",
    )
    parser.add_argument("--epochs", type=int, default=5)
    parser.add_argument("--batch_size", type=int, default=16)
    parser.add_argument(
        "--output",
        default=None,
        help="Path to save weights. Defaults to ./ml_models/retinaiq_<model>.h5",
    )
    args = parser.parse_args()

    random.seed(42)
    tf.random.set_seed(42)

    dataset_path = Path(args.dataset_path).expanduser().resolve()
    print(f"Loading dataset from: {dataset_path}")
    samples = _load_samples(dataset_path)
    train_samples, val_samples, test_samples = _stratified_split(samples)
    print(f"Split — train: {len(train_samples)}, val: {len(val_samples)}, test: {len(test_samples)}")

    train_ds = _build_dataset(train_samples, batch_size=args.batch_size, training=True)
    val_ds = _build_dataset(val_samples, batch_size=args.batch_size, training=False)
    test_ds = _build_dataset(test_samples, batch_size=args.batch_size, training=False)

    model = _build_model(args.model)
    class_weight = _class_weights(train_samples)

    callbacks = [
        tf.keras.callbacks.EarlyStopping(
            monitor="val_auc", mode="max", patience=5, restore_best_weights=True
        ),
        tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=2),
    ]

    print(f"\nTraining {args.model} for up to {args.epochs} epochs...")
    history = model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=args.epochs,
        class_weight=class_weight,
        callbacks=callbacks,
        verbose=1,
    )

    print("\nEvaluating on test set...")
    test_metrics = model.evaluate(test_ds, verbose=0)

    out_dir = Path("./ml_models")
    out_dir.mkdir(parents=True, exist_ok=True)

    output_path = Path(args.output) if args.output else out_dir / f"retinaiq_{args.model}.h5"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    model.save_weights(str(output_path))

    results = {
        "dataset_path": str(dataset_path),
        "model": args.model,
        "epochs_run": len(history.history.get("loss", [])),
        "epochs_max": args.epochs,
        "batch_size": args.batch_size,
        "train_samples": len(train_samples),
        "val_samples": len(val_samples),
        "test_samples": len(test_samples),
        "history": history.history,
        "test_loss": float(test_metrics[0]),
        "test_accuracy": float(test_metrics[1]),
        "test_auc": float(test_metrics[2]),
        "weights_saved_to": str(output_path),
    }
    history_path = out_dir / "training_history.json"
    history_path.write_text(json.dumps(results, indent=2), encoding="utf-8")

    print(f"\nTraining complete.")
    print(f"  Test accuracy : {test_metrics[1]:.4f}")
    print(f"  Test AUC      : {test_metrics[2]:.4f}")
    print(f"  Weights saved : {output_path}")
    print(f"  History saved : {history_path}")


if __name__ == "__main__":
    main()
