# Generated by GitHub Copilot
"""
RetinaIQ — Production-grade training pipeline for 5-class diabetic retinopathy grading.

Architecture strategy
---------------------
  • Two-phase transfer learning:
      Phase 1 — backbone frozen,  train head only        (fast convergence, no early overfitting)
      Phase 2 — unfreeze top 30 % of backbone, fine-tune end-to-end at 10× lower LR
  • Mixed precision (float16) on GPU — 2–3× throughput with identical accuracy
  • Cosine-decay LR with linear warm-up — stable early training, smooth late annealing
  • Label smoothing (ε=0.10) — improves calibration, reduces overconfident predictions
  • Dual-pooling head (GAP + GMP concatenated) — captures avg AND peak spatial activations
  • 360° rotation augmentation — valid for circular fundus images (no gravity orientation)
  • Inverse-frequency class weights — counters severe label imbalance in APTOS
  • ModelCheckpoint saves the single best epoch (by val_auc) across both phases

Usage
-----
    python train.py --dataset_path /path/to/dataset
    python train.py --dataset_path /path/to/dataset --model efficientnetv2b3 \\
                    --phase1_epochs 15 --phase2_epochs 20 --batch_size 16

Dataset layout:
    <dataset_path>/
        train.csv          # columns: id_code, diagnosis  (0 = No DR … 4 = PDR)
        train_images/      # or images/
            <id_code>.png

Outputs in ./ml_models/:
    retinaiq_<model>_best.h5    best weights across both phases (monitored by val_auc)
    training_history.json       per-epoch metrics for phase 1 and phase 2
    logs/<model>/               TensorBoard event files  →  tensorboard --logdir ml_models/logs
"""

import argparse
import csv
import json
import math
import random
from pathlib import Path

import numpy as np
import tensorflow as tf


# ── Learning-rate schedule ─────────────────────────────────────────────────

class WarmupCosineDecay(tf.keras.optimizers.schedules.LearningRateSchedule):
    """Linear warm-up for `warmup_steps`, then cosine decay to `min_lr`."""

    def __init__(
        self,
        peak_lr: float,
        warmup_steps: int,
        total_steps: int,
        min_lr: float = 1e-7,
    ) -> None:
        super().__init__()
        self.peak_lr = float(peak_lr)
        self.warmup_steps = float(warmup_steps)
        self.total_steps = float(total_steps)
        self.min_lr = float(min_lr)

    def __call__(self, step: tf.Tensor) -> tf.Tensor:
        step = tf.cast(step, tf.float32)
        warmup_lr = self.peak_lr * (step / self.warmup_steps)
        decay_progress = (step - self.warmup_steps) / (self.total_steps - self.warmup_steps)
        cosine_lr = self.min_lr + 0.5 * (self.peak_lr - self.min_lr) * (
            1.0 + tf.cos(math.pi * tf.clip_by_value(decay_progress, 0.0, 1.0))
        )
        return tf.where(step < self.warmup_steps, warmup_lr, cosine_lr)

    def get_config(self) -> dict:
        return {
            "peak_lr": self.peak_lr,
            "warmup_steps": self.warmup_steps,
            "total_steps": self.total_steps,
            "min_lr": self.min_lr,
        }


# ── Data utilities ─────────────────────────────────────────────────────────

def _find_image_file(images_dir: Path, image_id: str) -> Path | None:
    for ext in (".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"):
        p = images_dir / f"{image_id}{ext}"
        if p.exists():
            return p
    return None


def _load_samples(dataset_path: Path) -> list[tuple[str, int]]:
    csv_path = dataset_path / "train.csv"
    if not csv_path.exists():
        raise FileNotFoundError(f"train.csv not found at: {csv_path}")

    images_dir = dataset_path / "train_images"
    if not images_dir.exists():
        images_dir = dataset_path / "images"
    if not images_dir.exists():
        raise FileNotFoundError(
            "Image folder not found. Expected train_images/ or images/ inside dataset path."
        )

    rows: list[tuple[str, int]] = []
    with csv_path.open("r", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            img_id = str(row.get("id_code", "")).strip()
            label = int(str(row.get("diagnosis", "0")).strip())
            p = _find_image_file(images_dir, img_id)
            if p is not None:
                rows.append((str(p), label))

    if not rows:
        raise RuntimeError("No usable samples found — check dataset path and CSV content.")
    return rows


def _stratified_split(
    samples: list[tuple[str, int]],
    val_ratio: float = 0.15,
    test_ratio: float = 0.15,
) -> tuple[list[tuple[str, int]], list[tuple[str, int]], list[tuple[str, int]]]:
    by_class: dict[int, list[tuple[str, int]]] = {i: [] for i in range(5)}
    for s in samples:
        by_class[s[1]].append(s)

    train, val, test = [], [], []
    for items in by_class.values():
        if not items:
            continue
        random.shuffle(items)
        n = len(items)
        nv = max(1, int(n * val_ratio)) if n >= 3 else 1
        nt = max(1, int(n * test_ratio)) if n >= 3 else 1
        ntr = max(1, n - nv - nt)
        train.extend(items[:ntr])
        val.extend(items[ntr : ntr + nv])
        test.extend(items[ntr + nv :])

    random.shuffle(train)
    random.shuffle(val)
    random.shuffle(test)
    return train, val, test


def _make_augmenter() -> tf.keras.Sequential:
    """Fundus-optimised augmentation pipeline.

    360° rotation is valid because fundus images are circular discs with no
    gravity-dependent orientation.  Strong colour jitter accounts for the
    wide variation in fundus camera calibration across clinical sites.
    """
    return tf.keras.Sequential(
        [
            tf.keras.layers.RandomFlip("horizontal_and_vertical"),
            tf.keras.layers.RandomRotation(0.5),           # full 360° range
            tf.keras.layers.RandomZoom((-0.15, 0.10)),     # slight zoom in/out
            tf.keras.layers.RandomTranslation(0.05, 0.05), # centering offsets
            tf.keras.layers.RandomBrightness(0.25),        # camera exposure variation
            tf.keras.layers.RandomContrast(0.30),          # fundus quality variation
        ],
        name="augmenter",
    )


def _build_dataset(
    samples: list[tuple[str, int]],
    batch_size: int,
    training: bool,
    image_size: int = 300,
) -> tf.data.Dataset:
    paths = [s[0] for s in samples]
    labels = [s[1] for s in samples]
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))

    def _decode(path: tf.Tensor, label: tf.Tensor) -> tuple[tf.Tensor, tf.Tensor]:
        img = tf.io.read_file(path)
        img = tf.io.decode_image(img, channels=3, expand_animations=False)
        img = tf.image.resize(img, [image_size, image_size])
        img = tf.cast(img, tf.float32) / 255.0
        return img, tf.one_hot(tf.cast(label, tf.int32), depth=5)

    ds = ds.map(_decode, num_parallel_calls=tf.data.AUTOTUNE)
    if training:
        augmenter = _make_augmenter()
        ds = ds.map(
            lambda x, y: (augmenter(x, training=True), y),
            num_parallel_calls=tf.data.AUTOTUNE,
        )
        ds = ds.shuffle(
            buffer_size=max(len(samples), batch_size * 8),
            reshuffle_each_iteration=True,
        )

    return ds.batch(batch_size, drop_remainder=training).prefetch(tf.data.AUTOTUNE)


def _build_model(model_name: str, image_size: int = 300) -> tf.keras.Model:
    """Backbone + dual-pooling head for 5-class DR grading.

    Dual pooling (GAP + GMP concatenated) captures both average and peak
    spatial activations — a consistently effective trick for fine-grained
    classification tasks.
    """
    backbones = {
        "efficientnetv2b3": tf.keras.applications.EfficientNetV2B3,
        "efficientnetb0": tf.keras.applications.EfficientNetB0,
        "mobilenetv3": tf.keras.applications.MobileNetV3Large,
        "densenet121": tf.keras.applications.DenseNet121,
    }
    if model_name not in backbones:
        raise ValueError(f"Unknown model '{model_name}'. Choose from: {', '.join(backbones)}")

    backbone = backbones[model_name](
        weights="imagenet",
        include_top=False,
        input_shape=(image_size, image_size, 3),
        name="backbone",
    )
    backbone.trainable = False  # frozen during phase 1

    # Dual-pooling head
    gap = tf.keras.layers.GlobalAveragePooling2D()(backbone.output)
    gmp = tf.keras.layers.GlobalMaxPooling2D()(backbone.output)
    x = tf.keras.layers.Concatenate()([gap, gmp])
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dense(
        512, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(1e-4)
    )(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.4)(x)
    x = tf.keras.layers.Dense(
        256, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(1e-4)
    )(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.3)(x)
    # dtype="float32" ensures numerical stability when mixed precision is active
    out = tf.keras.layers.Dense(5, activation="softmax", dtype="float32")(x)

    return tf.keras.Model(inputs=backbone.input, outputs=out)


def _class_weights(train_samples: list[tuple[str, int]]) -> dict[int, float]:
    counts: dict[int, int] = {i: 0 for i in range(5)}
    for _, label in train_samples:
        counts[label] += 1
    total = sum(counts.values())
    return {k: (1.0 if v == 0 else total / (5.0 * v)) for k, v in counts.items()}


def _compile(model: tf.keras.Model, schedule: WarmupCosineDecay) -> None:
    model.compile(
        optimizer=tf.keras.optimizers.Adam(
            learning_rate=schedule,
            clipnorm=1.0,  # gradient clipping prevents explosions during fine-tuning
        ),
        loss=tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.10),
        metrics=[
            "accuracy",
            tf.keras.metrics.AUC(name="auc"),
        ],
    )


def _callbacks(output_path: Path, log_dir: Path, phase: int) -> list:
    return [
        tf.keras.callbacks.ModelCheckpoint(
            filepath=str(output_path),
            monitor="val_auc",
            mode="max",
            save_best_only=True,
            save_weights_only=True,
            verbose=1,
        ),
        tf.keras.callbacks.EarlyStopping(
            monitor="val_auc",
            mode="max",
            patience=7,
            restore_best_weights=True,
            verbose=1,
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss",
            factor=0.5,
            patience=3,
            min_lr=1e-8,
            verbose=1,
        ),
        tf.keras.callbacks.TensorBoard(
            log_dir=str(log_dir / f"phase{phase}"),
            histogram_freq=0,
            update_freq="epoch",
        ),
    ]


def _configure_precision() -> None:
    """Enable mixed-precision float16 on GPU for 2–3× throughput improvement."""
    if tf.config.list_physical_devices("GPU"):
        tf.keras.mixed_precision.set_global_policy("mixed_float16")
        print("Mixed precision (float16) enabled on GPU.")
    else:
        print("No GPU detected — running on CPU with float32.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Train a RetinaIQ DR grading model.")
    parser.add_argument("--dataset_path", required=True, help="Path to APTOS-style dataset.")
    parser.add_argument(
        "--model",
        default="efficientnetv2b3",
        choices=["efficientnetv2b3", "efficientnetb0", "mobilenetv3", "densenet121"],
        help="Backbone architecture (default: efficientnetv2b3).",
    )
    parser.add_argument(
        "--phase1_epochs", type=int, default=15,
        help="Epochs for head-only training with backbone frozen (default: 15).",
    )
    parser.add_argument(
        "--phase2_epochs", type=int, default=20,
        help="Epochs for end-to-end fine-tuning with top 30%% backbone unfrozen (default: 20).",
    )
    parser.add_argument("--batch_size", type=int, default=16)
    parser.add_argument(
        "--image_size", type=int, default=300,
        help="Input image size in pixels (default: 300). Must match evaluate.py.",
    )
    parser.add_argument(
        "--output", default=None,
        help="Weights output path. Default: ./ml_models/retinaiq_<model>_best.h5",
    )
    args = parser.parse_args()

    _configure_precision()
    random.seed(42)
    tf.random.set_seed(42)
    np.random.seed(42)

    dataset_path = Path(args.dataset_path).expanduser().resolve()
    out_dir = Path("./ml_models")
    out_dir.mkdir(parents=True, exist_ok=True)
    log_dir = out_dir / "logs" / args.model
    output_path = (
        Path(args.output) if args.output else out_dir / f"retinaiq_{args.model}_best.h5"
    )

    print(f"\nDataset : {dataset_path}")
    samples = _load_samples(dataset_path)
    train_samples, val_samples, test_samples = _stratified_split(samples)
    print(
        f"Split   — train: {len(train_samples)}  val: {len(val_samples)}  test: {len(test_samples)}"
    )

    train_ds = _build_dataset(train_samples, args.batch_size, training=True,  image_size=args.image_size)
    val_ds   = _build_dataset(val_samples,   args.batch_size, training=False, image_size=args.image_size)
    test_ds  = _build_dataset(test_samples,  args.batch_size, training=False, image_size=args.image_size)

    model = _build_model(args.model, image_size=args.image_size)
    class_weight = _class_weights(train_samples)
    steps_per_epoch = math.ceil(len(train_samples) / args.batch_size)

    # ── Phase 1: Head-only training ────────────────────────────────────────
    print(f"\n{'='*60}")
    print(f"Phase 1 — Head-only training  ({args.phase1_epochs} epochs max)")
    print(f"{'='*60}")
    p1_total = args.phase1_epochs * steps_per_epoch
    p1_warmup = max(1, steps_per_epoch)  # 1 epoch of linear warm-up
    _compile(model, WarmupCosineDecay(peak_lr=3e-4, warmup_steps=p1_warmup, total_steps=p1_total, min_lr=1e-6))

    p1_hist = model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=args.phase1_epochs,
        class_weight=class_weight,
        callbacks=_callbacks(output_path, log_dir, phase=1),
        verbose=1,
    )

    # ── Phase 2: Fine-tune top 30 % of backbone ────────────────────────────
    print(f"\n{'='*60}")
    print(f"Phase 2 — Fine-tuning top 30 % of backbone  ({args.phase2_epochs} epochs max)")
    print(f"{'='*60}")

    backbone_layer = model.get_layer("backbone")
    n_layers = len(backbone_layer.layers)
    unfreeze_from = int(n_layers * 0.70)  # top 30 %
    for layer in backbone_layer.layers[unfreeze_from:]:
        # Keep BatchNorm frozen to preserve running statistics from ImageNet pre-training
        if not isinstance(layer, tf.keras.layers.BatchNormalization):
            layer.trainable = True

    newly_trainable = sum(1 for l in backbone_layer.layers[unfreeze_from:]
                          if not isinstance(l, tf.keras.layers.BatchNormalization))
    print(f"Unfrozen {newly_trainable} backbone layers (BatchNorm layers kept frozen).")

    p2_total = args.phase2_epochs * steps_per_epoch
    p2_warmup = max(1, steps_per_epoch // 2)
    # 10× lower peak LR than phase 1 — safe fine-tuning of pretrained features
    _compile(model, WarmupCosineDecay(peak_lr=3e-5, warmup_steps=p2_warmup, total_steps=p2_total, min_lr=1e-8))

    p2_hist = model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=args.phase2_epochs,
        class_weight=class_weight,
        callbacks=_callbacks(output_path, log_dir, phase=2),
        verbose=1,
    )

    # ── Final evaluation on held-out test set ──────────────────────────────
    print("\nLoading best checkpoint weights for final test evaluation...")
    model.load_weights(str(output_path))
    test_metrics = model.evaluate(test_ds, verbose=1)

    results = {
        "model": args.model,
        "dataset_path": str(dataset_path),
        "image_size": args.image_size,
        "batch_size": args.batch_size,
        "phase1_epochs_run": len(p1_hist.history.get("loss", [])),
        "phase2_epochs_run": len(p2_hist.history.get("loss", [])),
        "train_samples": len(train_samples),
        "val_samples": len(val_samples),
        "test_samples": len(test_samples),
        "phase1_history": p1_hist.history,
        "phase2_history": p2_hist.history,
        "test_loss": float(test_metrics[0]),
        "test_accuracy": float(test_metrics[1]),
        "test_auc": float(test_metrics[2]),
        "weights_saved_to": str(output_path),
    }
    history_path = out_dir / "training_history.json"
    history_path.write_text(json.dumps(results, indent=2), encoding="utf-8")

    print(f"\n{'='*60}")
    print("Training complete.")
    print(f"  Test accuracy : {test_metrics[1]:.4f}")
    print(f"  Test AUC      : {test_metrics[2]:.4f}")
    print(f"  Weights saved : {output_path}")
    print(f"  History saved : {history_path}")
    print(f"  TensorBoard   : tensorboard --logdir {log_dir}")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
