// Generated by GitHub Copilot
import { LayoutDashboard, ScanEye, Users, FileText, Settings } from "lucide-react";
import { Link, useLocation } from "react-router-dom";

const links = [
  { to: "/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { to: "/analyze", label: "Analyze", icon: ScanEye },
  { to: "/patients", label: "Patients", icon: Users },
  { to: "/reports", label: "Reports", icon: FileText },
  { to: "/settings", label: "Settings", icon: Settings },
];

export function Sidebar(): JSX.Element {
  const location = useLocation();
  return (
    <aside className="w-60 bg-slate-950/60 border-r border-white/10 p-4">
      <h2 className="font-bold text-xl mb-4">RetinaIQ</h2>
      <nav className="space-y-2">
        {links.map((link) => {
          const Icon = link.icon;
          const active = location.pathname === link.to;
          return (
            <Link
              key={link.to}
              to={link.to}
              className={`flex items-center gap-2 rounded-lg px-3 py-2 ${
                active ? "bg-emerald-500/20 text-emerald-300" : "text-slate-300 hover:bg-slate-800"
              }`}
            >
              <Icon size={16} />
              {link.label}
            </Link>
          );
        })}
      </nav>
    </aside>
  );
}
