// Generated by GitHub Copilot
import { useMemo, useState } from "react";
import { useDropzone } from "react-dropzone";
import { Sidebar } from "../components/Sidebar";

export function AnalyzePage(): JSX.Element {
  const [preview, setPreview] = useState<string | null>(null);
  const [result, setResult] = useState<{ grade: number; confidence: number } | null>(null);

  const onDrop = useMemo(
    () =>
      (acceptedFiles: File[]) => {
        const file = acceptedFiles[0];
        if (!file) return;
        setPreview(URL.createObjectURL(file));
      },
    [],
  );

  const { getRootProps, getInputProps, isDragActive } = useDropzone({ onDrop });

  return (
    <div className="min-h-screen flex">
      <Sidebar />
      <main className="flex-1 p-8 grid grid-cols-1 xl:grid-cols-2 gap-6">
        <section className="bg-slate-900/60 border border-white/10 rounded-2xl p-6">
          <h2 className="text-2xl mb-4">Upload and Configure</h2>
          <div
            {...getRootProps()}
            className={`h-80 rounded-2xl border-2 border-dashed flex items-center justify-center text-center p-4 ${
              isDragActive ? "border-emerald-300 bg-emerald-500/10" : "border-emerald-500/40"
            }`}
          >
            <input {...getInputProps()} />
            {preview ? (
              <img src={preview} alt="Retinal preview" className="h-full w-full object-cover rounded-xl" />
            ) : (
              <div>
                <p className="text-lg">Drop retinal image here</p>
                <p className="text-slate-400">JPG, PNG, TIFF, BMP, DICOM</p>
              </div>
            )}
          </div>
          <button
            className="glow-btn mt-5"
            onClick={() => setResult({ grade: 2, confidence: 87.4 })}
            disabled={!preview}
          >
            Analyze Image
          </button>
        </section>
        <section className="bg-slate-900/60 border border-white/10 rounded-2xl p-6">
          <h2 className="text-2xl mb-4">Results</h2>
          {!result ? (
            <p className="text-slate-400">Results will appear here after analysis.</p>
          ) : (
            <div>
              <p className="text-4xl font-mono">Grade {result.grade}</p>
              <p className="text-slate-300">Confidence {result.confidence}%</p>
              {preview && <img className="mt-4 rounded-xl" src={preview} alt="Grad-CAM view" />}
              <p className="mt-4 text-sm text-slate-400">
                This output is AI-generated and must be reviewed by a qualified ophthalmologist before any clinical decision.
              </p>
            </div>
          )}
        </section>
      </main>
    </div>
  );
}
