// Generated by GitHub Copilot
import { PieChart, Pie, Cell, Tooltip } from "recharts";
import { Sidebar } from "../components/Sidebar";

const data = [
  { name: "No DR", value: 30, color: "#22C55E" },
  { name: "Mild", value: 20, color: "#84CC16" },
  { name: "Moderate", value: 25, color: "#F59E0B" },
  { name: "Severe", value: 15, color: "#F97316" },
  { name: "PDR", value: 10, color: "#EF4444" },
];

export function DashboardPage(): JSX.Element {
  return (
    <div className="min-h-screen flex">
      <Sidebar />
      <main className="flex-1 p-8">
        <h1 className="text-3xl font-semibold mb-8">Dashboard</h1>
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4 mb-8">
          {[
            ["Total Scans", "1247"],
            ["This Week", "43"],
            ["Avg Confidence", "83.1%"],
            ["Pending Review", "18"],
          ].map(([label, value]) => (
            <div key={label} className="bg-slate-900/60 border border-white/10 rounded-2xl p-5">
              <p className="text-slate-400">{label}</p>
              <p className="text-4xl font-mono mt-2">{value}</p>
            </div>
          ))}
        </div>
        <div className="bg-slate-900/60 border border-white/10 rounded-2xl p-6 w-fit">
          <PieChart width={320} height={320}>
            <Pie data={data} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={120}>
              {data.map((entry) => (
                <Cell key={entry.name} fill={entry.color} />
              ))}
            </Pie>
            <Tooltip />
          </PieChart>
        </div>
      </main>
    </div>
  );
}
