// Generated by GitHub Copilot
import { motion } from "framer-motion";
import { Link } from "react-router-dom";

export function LandingPage(): JSX.Element {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center text-center px-6">
      <motion.h1
        initial={{ y: 16, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ duration: 0.6 }}
        className="text-6xl font-bold"
        style={{ fontFamily: "var(--font-display)" }}
      >
        See What Others <span style={{ color: "var(--accent-primary)" }}>Miss.</span>
      </motion.h1>
      <p className="mt-6 text-xl text-slate-300 max-w-2xl">
        AI-powered diabetic retinopathy screening with clinical-grade explainability.
      </p>
      <div className="flex gap-4 mt-8">
        <Link className="glow-btn" to="/analyze">
          Begin Screening
        </Link>
        <a className="glow-btn" href="#research">
          Read the Research
        </a>
      </div>
    </main>
  );
}
