// Generated by GitHub Copilot
import { useState } from "react";
import { useNavigate } from "react-router-dom";

export function LoginPage(): JSX.Element {
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  return (
    <main className="min-h-screen grid grid-cols-1 md:grid-cols-2">
      <section className="hidden md:flex items-center justify-center bg-slate-950/40">
        <h2 className="text-4xl">Retinal Sweep Visualization</h2>
      </section>
      <section className="flex items-center justify-center p-6">
        <form
          className="w-full max-w-md bg-slate-900/60 border border-white/10 rounded-2xl p-8 space-y-4"
          onSubmit={(e) => {
            e.preventDefault();
            navigate("/dashboard");
          }}
        >
          <h1 className="text-3xl font-semibold">Welcome back</h1>
          <p className="text-slate-300">RetinaIQ Clinical Portal</p>
          <input
            className="w-full rounded-xl bg-slate-800 p-3"
            placeholder="Email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
          <input
            className="w-full rounded-xl bg-slate-800 p-3"
            placeholder="Password"
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
          <button className="glow-btn w-full" type="submit">
            Sign In
          </button>
        </form>
      </section>
    </main>
  );
}
