// Generated by GitHub Copilot
import { LineChart, Line, XAxis, YAxis, Tooltip } from "recharts";
import { Sidebar } from "../components/Sidebar";

const history = [
  { date: "2026-01-10", grade: 1 },
  { date: "2026-02-10", grade: 2 },
  { date: "2026-03-10", grade: 2 },
];

export function PatientDetailPage(): JSX.Element {
  return (
    <div className="min-h-screen flex">
      <Sidebar />
      <main className="flex-1 p-8 space-y-6">
        <section className="bg-slate-900/60 border border-white/10 rounded-2xl p-6">
          <h1 className="text-3xl">Patient Detail</h1>
          <p className="text-slate-300 mt-2">Diabetes duration: 8 years | HbA1c: 7.4%</p>
        </section>
        <section className="bg-slate-900/60 border border-white/10 rounded-2xl p-6">
          <h2 className="text-2xl mb-4">Grade Progression</h2>
          <LineChart width={700} height={260} data={history}>
            <XAxis dataKey="date" />
            <YAxis domain={[0, 4]} />
            <Tooltip />
            <Line type="monotone" dataKey="grade" stroke="#00D4AA" strokeWidth={3} />
          </LineChart>
        </section>
      </main>
    </div>
  );
}
