// Generated by GitHub Copilot
import { Link } from "react-router-dom";
import { Sidebar } from "../components/Sidebar";

const patients = [
  { id: "p1", name: "Ananya Reddy", code: "CBIT-001", scans: 4, latest: "Moderate" },
  { id: "p2", name: "Rahul Sharma", code: "CBIT-002", scans: 2, latest: "Mild" },
];

export function PatientsPage(): JSX.Element {
  return (
    <div className="min-h-screen flex">
      <Sidebar />
      <main className="flex-1 p-8">
        <h1 className="text-3xl mb-6">Patients</h1>
        <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">
          {patients.map((patient) => (
            <article key={patient.id} className="bg-slate-900/60 border border-white/10 rounded-2xl p-5">
              <h2 className="text-xl">{patient.name}</h2>
              <p className="text-slate-400 font-mono">{patient.code}</p>
              <p className="mt-3">{patient.scans} scans</p>
              <p>Latest grade: {patient.latest}</p>
              <Link className="inline-block mt-4 text-emerald-300" to={`/patients/${patient.id}`}>
                View history
              </Link>
            </article>
          ))}
        </div>
      </main>
    </div>
  );
}
