// Generated by GitHub Copilot
import { Sidebar } from "../components/Sidebar";

const reports = [
  { id: "r1", patient: "Ananya Reddy", grade: "Moderate", confidence: "87.4%", date: "2026-03-12" },
  { id: "r2", patient: "Rahul Sharma", grade: "Mild", confidence: "73.2%", date: "2026-03-11" },
];

export function ReportsPage(): JSX.Element {
  return (
    <div className="min-h-screen flex">
      <Sidebar />
      <main className="flex-1 p-8">
        <h1 className="text-3xl mb-6">Reports</h1>
        <div className="bg-slate-900/60 border border-white/10 rounded-2xl overflow-hidden">
          <table className="w-full">
            <thead className="bg-slate-800/60">
              <tr>
                <th className="text-left p-3">Date</th>
                <th className="text-left p-3">Patient</th>
                <th className="text-left p-3">Grade</th>
                <th className="text-left p-3">Confidence</th>
                <th className="text-left p-3">Actions</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((report) => (
                <tr key={report.id} className="border-t border-white/10">
                  <td className="p-3">{report.date}</td>
                  <td className="p-3">{report.patient}</td>
                  <td className="p-3">{report.grade}</td>
                  <td className="p-3">{report.confidence}</td>
                  <td className="p-3">
                    <button className="glow-btn">Download PDF</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </div>
  );
}
